[package]
name = "dosio"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"

[workspace]
members = ["dosio-proc"]

[dependencies]
serde = { version = "1.0.124", features = ["derive"] }
dosio-proc = { path = "dosio-proc" }

[dev-dependencies]
serde-pickle = "0.6.2"
