[package]
name = "dosio-proc"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" , branch= "master" }
